// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inventory_transactions.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInventoryTransactionBatch = `-- name: CreateInventoryTransactionBatch :exec
INSERT INTO inventory_transactions (
    id,
    inventory_id,
    type,
    quantity,
    balance_before,
    balance_after,
    reference_type,
    reference_id,
    action_type,
    idempotency_key,
    note,
    created_by,
    created_at
) SELECT
    unnest($1::uuid[]),
    unnest($2::uuid[]),
    unnest($3::text[]),
    unnest($4::bigint[]),
    unnest($5::bigint[]),
    unnest($6::bigint[]),
    unnest($7::text[]),
    unnest($8::text[]),
    unnest($9::text[]),
    unnest($10::text[]),
    unnest($11::text[]),
    unnest($12::uuid[]),
    unnest($13::timestamptz[])
`

type CreateInventoryTransactionBatchParams struct {
	Ids             []pgtype.UUID
	InventoryIds    []pgtype.UUID
	Types           []string
	Quantities      []int64
	BalancesBefore  []int64
	BalancesAfter   []int64
	ReferenceTypes  []string
	ReferenceIds    []string
	ActionTypes     []string
	IdempotencyKeys []string
	Notes           []string
	CreatedBys      []pgtype.UUID
	CreatedAts      []pgtype.Timestamptz
}

func (q *Queries) CreateInventoryTransactionBatch(ctx context.Context, arg CreateInventoryTransactionBatchParams) error {
	_, err := q.db.Exec(ctx, createInventoryTransactionBatch,
		arg.Ids,
		arg.InventoryIds,
		arg.Types,
		arg.Quantities,
		arg.BalancesBefore,
		arg.BalancesAfter,
		arg.ReferenceTypes,
		arg.ReferenceIds,
		arg.ActionTypes,
		arg.IdempotencyKeys,
		arg.Notes,
		arg.CreatedBys,
		arg.CreatedAts,
	)
	return err
}
