// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inventories.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInventoryItemsBatch = `-- name: CreateInventoryItemsBatch :exec
INSERT INTO inventories (
    id,
    sku_id,
    shop_id,
    quantity,
    reserved,
    status,
    created_by,
    updated_by,
    created_at,
    updated_at
)
SELECT
    unnest($1::uuid[]),
    unnest($2::uuid[]),
    $3::uuid,
    unnest($4::bigint[]),
    unnest($5::bigint[]),
    unnest($6::text[]),
    $7::uuid,
    $8::uuid,
    $9::timestamptz,
    NULL::timestamptz
`

type CreateInventoryItemsBatchParams struct {
	Ids                []pgtype.UUID
	SkuIds             []pgtype.UUID
	ShopID             pgtype.UUID
	Quantities         []int64
	ReservedQuantities []int64
	Statuses           []string
	CreatedBy          pgtype.UUID
	UpdatedBy          pgtype.UUID
	CreatedAt          pgtype.Timestamptz
}

func (q *Queries) CreateInventoryItemsBatch(ctx context.Context, arg CreateInventoryItemsBatchParams) error {
	_, err := q.db.Exec(ctx, createInventoryItemsBatch,
		arg.Ids,
		arg.SkuIds,
		arg.ShopID,
		arg.Quantities,
		arg.ReservedQuantities,
		arg.Statuses,
		arg.CreatedBy,
		arg.UpdatedBy,
		arg.CreatedAt,
	)
	return err
}

const fulfillInventoryStockBatch = `-- name: FulfillInventoryStockBatch :execrows
UPDATE inventories AS i
SET
    quantity = i.quantity - u.req_quantity,
    reserved = i.reserved - u.req_quantity,
    updated_by = $1::uuid,
    updated_at = $2::timestamptz
FROM (
    SELECT inventory_id, req_quantity FROM ROWS FROM (
        unnest($4::uuid[]),
        unnest($5::bigint[])
    ) AS tmp(inventory_id, req_quantity)
) AS u
WHERE i.shop_id = $3::uuid
    AND i.id = u.inventory_id
    AND i.quantity >= u.req_quantity
    AND i.reserved >= u.req_quantity
`

type FulfillInventoryStockBatchParams struct {
	ActorID      pgtype.UUID
	UpdatedAt    pgtype.Timestamptz
	ShopID       pgtype.UUID
	InventoryIds []pgtype.UUID
	Quantities   []int64
}

func (q *Queries) FulfillInventoryStockBatch(ctx context.Context, arg FulfillInventoryStockBatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, fulfillInventoryStockBatch,
		arg.ActorID,
		arg.UpdatedAt,
		arg.ShopID,
		arg.InventoryIds,
		arg.Quantities,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveInventoryItemByShopAndSku = `-- name: GetActiveInventoryItemByShopAndSku :one
SELECT
    id,
    sku_id,
    shop_id,
    quantity,
    reserved,
    status,
    created_by,
    updated_by,
    created_at,
    updated_at
FROM inventories
WHERE shop_id = $1::uuid
  AND sku_id = $2::uuid
  AND status = $3::text
LIMIT 1
`

type GetActiveInventoryItemByShopAndSkuParams struct {
	ShopID       pgtype.UUID
	SkuID        pgtype.UUID
	ActiveStatus string
}

func (q *Queries) GetActiveInventoryItemByShopAndSku(ctx context.Context, arg GetActiveInventoryItemByShopAndSkuParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, getActiveInventoryItemByShopAndSku, arg.ShopID, arg.SkuID, arg.ActiveStatus)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.SkuID,
		&i.ShopID,
		&i.Quantity,
		&i.Reserved,
		&i.Status,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInventoryItemsBySkuIDs = `-- name: ListInventoryItemsBySkuIDs :many
SELECT
    id,
    sku_id,
    shop_id,
    quantity,
    reserved,
    status,
    created_by,
    updated_by,
    created_at,
    updated_at
FROM inventories
WHERE sku_id = ANY($1::uuid[])
ORDER BY created_at ASC
`

func (q *Queries) ListInventoryItemsBySkuIDs(ctx context.Context, skuIds []pgtype.UUID) ([]Inventory, error) {
	rows, err := q.db.Query(ctx, listInventoryItemsBySkuIDs, skuIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Inventory
	for rows.Next() {
		var i Inventory
		if err := rows.Scan(
			&i.ID,
			&i.SkuID,
			&i.ShopID,
			&i.Quantity,
			&i.Reserved,
			&i.Status,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseInventoryStockBatch = `-- name: ReleaseInventoryStockBatch :execrows
UPDATE inventories AS i
SET
    reserved = i.reserved - u.req_quantity,
    updated_by = $1::uuid,
    updated_at = $2::timestamptz
FROM (
    SELECT inventory_id, req_quantity FROM ROWS FROM (
        unnest($4::uuid[]),
        unnest($5::bigint[])
    ) AS tmp(inventory_id, req_quantity)
) AS u
WHERE i.shop_id = $3::uuid
    AND i.id = u.inventory_id
    AND i.reserved >= u.req_quantity
`

type ReleaseInventoryStockBatchParams struct {
	ActorID      pgtype.UUID
	UpdatedAt    pgtype.Timestamptz
	ShopID       pgtype.UUID
	InventoryIds []pgtype.UUID
	Quantities   []int64
}

func (q *Queries) ReleaseInventoryStockBatch(ctx context.Context, arg ReleaseInventoryStockBatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseInventoryStockBatch,
		arg.ActorID,
		arg.UpdatedAt,
		arg.ShopID,
		arg.InventoryIds,
		arg.Quantities,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reserveInventoryStockBatch = `-- name: ReserveInventoryStockBatch :execrows
UPDATE inventories AS i
SET 
    reserved = i.reserved + u.req_quantity,
    updated_by = $1::uuid,
    created_at = $2::timestamptz
FROM (
    SELECT inventory_id, req_quantity FROM ROWS FROM (
        unnest($4::uuid[]), 
        unnest($5::bigint[])
    ) AS tmp(inventory_id, req_quantity)
) AS u
WHERE i.shop_id = $3::uuid
  AND i.id = u.inventory_id
  AND (i.quantity - i.reserved) >= u.req_quantity
`

type ReserveInventoryStockBatchParams struct {
	ActorID      pgtype.UUID
	CreatedAt    pgtype.Timestamptz
	ShopID       pgtype.UUID
	InventoryIds []pgtype.UUID
	Quantities   []int64
}

func (q *Queries) ReserveInventoryStockBatch(ctx context.Context, arg ReserveInventoryStockBatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, reserveInventoryStockBatch,
		arg.ActorID,
		arg.CreatedAt,
		arg.ShopID,
		arg.InventoryIds,
		arg.Quantities,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteInventoryItemsBySkuIDs = `-- name: SoftDeleteInventoryItemsBySkuIDs :execrows
UPDATE inventories
SET
    status = $1::text,
    updated_by = $2::uuid,
    updated_at = $3::timestamptz
WHERE sku_id = ANY($4::uuid[])
  AND status = $5::text
`

type SoftDeleteInventoryItemsBySkuIDsParams struct {
	DeletedStatus string
	ActorID       pgtype.UUID
	UpdatedAt     pgtype.Timestamptz
	SkuIds        []pgtype.UUID
	ActiveStatus  string
}

func (q *Queries) SoftDeleteInventoryItemsBySkuIDs(ctx context.Context, arg SoftDeleteInventoryItemsBySkuIDsParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteInventoryItemsBySkuIDs,
		arg.DeletedStatus,
		arg.ActorID,
		arg.UpdatedAt,
		arg.SkuIds,
		arg.ActiveStatus,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
