// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inventory_reservations.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInventoryReservationBatch = `-- name: CreateInventoryReservationBatch :exec
INSERT INTO inventory_reservations (
    id,
    inventory_id,
    order_id,
    quantity,
    status,
    expires_at,
    created_at,
    updated_at
) SELECT
    unnest($1::uuid[]),
    unnest($2::uuid[]),
    unnest($3::text[]),
    $4::text,
    $5::timestamptz,
    $6::timestamptz,
    $7::timestamptz
`

type CreateInventoryReservationBatchParams struct {
	Ids          []pgtype.UUID
	InventoryIds []pgtype.UUID
	OrderIds     []string
	Status       string
	ExpiresAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) CreateInventoryReservationBatch(ctx context.Context, arg CreateInventoryReservationBatchParams) error {
	_, err := q.db.Exec(ctx, createInventoryReservationBatch,
		arg.Ids,
		arg.InventoryIds,
		arg.OrderIds,
		arg.Status,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const fulfillReservationsByOrderID = `-- name: FulfillReservationsByOrderID :many
UPDATE inventory_reservations
SET
    status = 'COMPLETED',
    updated_at = $1::timestamptz
WHERE order_id = $2::text 
    AND status = 'HOLD'
RETURNING id, inventory_id, sku_id, shop_id, order_id, quantity, status, expires_at, created_at, updated_at
`

type FulfillReservationsByOrderIDParams struct {
	UpdatedAt pgtype.Timestamptz
	OrderID   string
}

func (q *Queries) FulfillReservationsByOrderID(ctx context.Context, arg FulfillReservationsByOrderIDParams) ([]InventoryReservation, error) {
	rows, err := q.db.Query(ctx, fulfillReservationsByOrderID, arg.UpdatedAt, arg.OrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InventoryReservation
	for rows.Next() {
		var i InventoryReservation
		if err := rows.Scan(
			&i.ID,
			&i.InventoryID,
			&i.SkuID,
			&i.ShopID,
			&i.OrderID,
			&i.Quantity,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseReservationsByOrderID = `-- name: ReleaseReservationsByOrderID :many
UPDATE inventory_reservations
SET
    status = 'RELEASED',
    updated_at = $1::timestamptz
WHERE order_id = $2::text 
    AND status = 'HOLD'
RETURNING id, inventory_id, sku_id, shop_id, order_id, quantity, status, expires_at, created_at, updated_at
`

type ReleaseReservationsByOrderIDParams struct {
	UpdatedAt pgtype.Timestamptz
	OrderID   string
}

func (q *Queries) ReleaseReservationsByOrderID(ctx context.Context, arg ReleaseReservationsByOrderIDParams) ([]InventoryReservation, error) {
	rows, err := q.db.Query(ctx, releaseReservationsByOrderID, arg.UpdatedAt, arg.OrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InventoryReservation
	for rows.Next() {
		var i InventoryReservation
		if err := rows.Scan(
			&i.ID,
			&i.InventoryID,
			&i.SkuID,
			&i.ShopID,
			&i.OrderID,
			&i.Quantity,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
