// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Inventory struct {
	ID        pgtype.UUID
	SkuID     pgtype.UUID
	ShopID    pgtype.UUID
	Quantity  int64
	Reserved  int64
	Status    string
	CreatedBy pgtype.UUID
	UpdatedBy pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type InventoryReservation struct {
	ID          pgtype.UUID
	InventoryID pgtype.UUID
	SkuID       pgtype.UUID
	ShopID      pgtype.UUID
	OrderID     string
	Quantity    int64
	Status      string
	ExpiresAt   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type InventoryTransaction struct {
	ID             pgtype.UUID
	InventoryID    pgtype.UUID
	Type           string
	Quantity       int64
	BalanceBefore  int64
	BalanceAfter   int64
	ReferenceType  string
	ReferenceID    string
	ActionType     string
	IdempotencyKey pgtype.Text
	Note           pgtype.Text
	CreatedBy      pgtype.UUID
	CreatedAt      pgtype.Timestamptz
}

type Outbox struct {
	ID             pgtype.UUID
	AggregateID    pgtype.UUID
	AggregateType  string
	EventType      string
	Payload        []byte
	PartitionKey   string
	IdempotencyKey pgtype.UUID
	CreatedAt      pgtype.Timestamptz
}
