// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID               string
	ShopID           pgtype.UUID
	BuyerID          pgtype.UUID
	Status           string
	ShippingName     string
	ShippingPhone    string
	ShippingAddress  string
	ShippingProvince string
	ShippingWard     string
	Note             pgtype.Text
	GrandTotal       int64
	Currency         string
	CancelReason     pgtype.Text
	CancelledBy      pgtype.UUID
	ConfirmedAt      pgtype.Timestamptz
	DeliveredAt      pgtype.Timestamptz
	ShippedAt        pgtype.Timestamptz
	CompletedAt      pgtype.Timestamptz
	CancelledAt      pgtype.Timestamptz
	FailedAt         pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	IdempotencyKey   pgtype.Text
}

type OrderHistory struct {
	ID         pgtype.UUID
	OrderID    string
	FromStatus pgtype.Text
	ToStatus   string
	ChangedBy  pgtype.UUID
	ActorType  string
	Reason     string
	CreatedAt  pgtype.Timestamptz
}

type OrderItem struct {
	ID           pgtype.UUID
	OrderID      string
	InventoryID  pgtype.UUID
	SkuID        pgtype.UUID
	SkuCode      string
	ProductID    pgtype.UUID
	ProductName  string
	ImageUrl     string
	Quantity     int64
	BasePrice    int64
	ItemSubtotal int64
	Currency     string
	CreatedAt    pgtype.Timestamptz
}

type Outbox struct {
	ID             pgtype.UUID
	AggregateID    pgtype.UUID
	AggregateType  string
	EventType      string
	Payload        []byte
	PartitionKey   string
	IdempotencyKey pgtype.UUID
	CreatedAt      pgtype.Timestamptz
}
