// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :exec
INSERT INTO orders (
    id,
    shop_id,
    buyer_id,
    idempotency_key,
    status,
    shipping_name,
    shipping_phone,
    shipping_address,
    shipping_province,
    shipping_ward,
    note,
    grand_total,
    currency,
    cancel_reason,
    cancelled_by,
    confirmed_at,
    delivered_at,
    shipped_at,
    completed_at,
    cancelled_at,
    failed_at,
    created_at
) VALUES (
    $1::text,
    $2::uuid,
    $3::uuid,
    $4::text,
    $5::text,
    $6::text,
    $7::text,
    $8::text,
    $9::text,
    $10::text,
    $11::text,
    $12::bigint,
    $13::text,
    $14::text,
    $15::uuid,
    $16::timestamptz,
    $17::timestamptz,
    $18::timestamptz,
    $19::timestamptz,
    $20::timestamptz,
    $21::timestamptz,
    $22::timestamptz
)
`

type CreateOrderParams struct {
	ID               string
	ShopID           pgtype.UUID
	BuyerID          pgtype.UUID
	IdempotencyKey   string
	Status           string
	ShippingName     string
	ShippingPhone    string
	ShippingAddress  string
	ShippingProvince string
	ShippingWard     string
	Note             string
	GrandTotal       int64
	Currency         string
	CancelReason     string
	CancelledBy      pgtype.UUID
	ConfirmedAt      pgtype.Timestamptz
	DeliveredAt      pgtype.Timestamptz
	ShippedAt        pgtype.Timestamptz
	CompletedAt      pgtype.Timestamptz
	CancelledAt      pgtype.Timestamptz
	FailedAt         pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) error {
	_, err := q.db.Exec(ctx, createOrder,
		arg.ID,
		arg.ShopID,
		arg.BuyerID,
		arg.IdempotencyKey,
		arg.Status,
		arg.ShippingName,
		arg.ShippingPhone,
		arg.ShippingAddress,
		arg.ShippingProvince,
		arg.ShippingWard,
		arg.Note,
		arg.GrandTotal,
		arg.Currency,
		arg.CancelReason,
		arg.CancelledBy,
		arg.ConfirmedAt,
		arg.DeliveredAt,
		arg.ShippedAt,
		arg.CompletedAt,
		arg.CancelledAt,
		arg.FailedAt,
		arg.CreatedAt,
	)
	return err
}

const getOrderByBuyerAndIdempotencyKey = `-- name: GetOrderByBuyerAndIdempotencyKey :one
SELECT id, shop_id, buyer_id, status, shipping_name, shipping_phone, shipping_address, shipping_province, shipping_ward, note, grand_total, currency, cancel_reason, cancelled_by, confirmed_at, delivered_at, shipped_at, completed_at, cancelled_at, failed_at, created_at, idempotency_key
FROM orders
WHERE buyer_id = $1::uuid
  AND idempotency_key = $2::text
LIMIT 1
`

type GetOrderByBuyerAndIdempotencyKeyParams struct {
	BuyerID        pgtype.UUID
	IdempotencyKey string
}

func (q *Queries) GetOrderByBuyerAndIdempotencyKey(ctx context.Context, arg GetOrderByBuyerAndIdempotencyKeyParams) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByBuyerAndIdempotencyKey, arg.BuyerID, arg.IdempotencyKey)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.BuyerID,
		&i.Status,
		&i.ShippingName,
		&i.ShippingPhone,
		&i.ShippingAddress,
		&i.ShippingProvince,
		&i.ShippingWard,
		&i.Note,
		&i.GrandTotal,
		&i.Currency,
		&i.CancelReason,
		&i.CancelledBy,
		&i.ConfirmedAt,
		&i.DeliveredAt,
		&i.ShippedAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, shop_id, buyer_id, status, shipping_name, shipping_phone, shipping_address, shipping_province, shipping_ward, note, grand_total, currency, cancel_reason, cancelled_by, confirmed_at, delivered_at, shipped_at, completed_at, cancelled_at, failed_at, created_at, idempotency_key
FROM orders
WHERE id = $1::text
LIMIT 1
`

func (q *Queries) GetOrderByID(ctx context.Context, id string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.BuyerID,
		&i.Status,
		&i.ShippingName,
		&i.ShippingPhone,
		&i.ShippingAddress,
		&i.ShippingProvince,
		&i.ShippingWard,
		&i.Note,
		&i.GrandTotal,
		&i.Currency,
		&i.CancelReason,
		&i.CancelledBy,
		&i.ConfirmedAt,
		&i.DeliveredAt,
		&i.ShippedAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :execrows
UPDATE orders
SET
    status = $1::text,
    cancel_reason = $2::text,
    cancelled_by = $3::uuid,
    confirmed_at = $4::timestamptz,
    delivered_at = $5::timestamptz,
    shipped_at = $6::timestamptz,
    completed_at = $7::timestamptz,
    cancelled_at = $8::timestamptz,
    failed_at = $9::timestamptz
WHERE id = $10::text
  AND status = $11::text
`

type UpdateOrderStatusParams struct {
	Status         string
	CancelReason   string
	CancelledBy    pgtype.UUID
	ConfirmedAt    pgtype.Timestamptz
	DeliveredAt    pgtype.Timestamptz
	ShippedAt      pgtype.Timestamptz
	CompletedAt    pgtype.Timestamptz
	CancelledAt    pgtype.Timestamptz
	FailedAt       pgtype.Timestamptz
	ID             string
	ExpectedStatus string
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateOrderStatus,
		arg.Status,
		arg.CancelReason,
		arg.CancelledBy,
		arg.ConfirmedAt,
		arg.DeliveredAt,
		arg.ShippedAt,
		arg.CompletedAt,
		arg.CancelledAt,
		arg.FailedAt,
		arg.ID,
		arg.ExpectedStatus,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
