// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order_history.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrderHistoryBatch = `-- name: CreateOrderHistoryBatch :exec
INSERT INTO order_history (
    id,
    order_id,
    from_status,
    to_status,
    changed_by,
    actor_type,
    reason,
    created_at
)
SELECT
    unnest($1::uuid[]),
    $2::text,
    unnest($3::text[]),
    unnest($4::text[]),
    unnest($5::uuid[]),
    unnest($6::text[]),
    unnest($7::text[]),
    $8::timestamptz
`

type CreateOrderHistoryBatchParams struct {
	Ids          []pgtype.UUID
	OrderID      string
	FromStatuses []string
	ToStatuses   []string
	ChangedBys   []pgtype.UUID
	ActorTypes   []string
	Reasons      []string
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) CreateOrderHistoryBatch(ctx context.Context, arg CreateOrderHistoryBatchParams) error {
	_, err := q.db.Exec(ctx, createOrderHistoryBatch,
		arg.Ids,
		arg.OrderID,
		arg.FromStatuses,
		arg.ToStatuses,
		arg.ChangedBys,
		arg.ActorTypes,
		arg.Reasons,
		arg.CreatedAt,
	)
	return err
}

const listOrderHistoryByOrderID = `-- name: ListOrderHistoryByOrderID :many
SELECT id, order_id, from_status, to_status, changed_by, actor_type, reason, created_at
FROM order_history
WHERE order_id = $1::text
ORDER BY created_at ASC
`

func (q *Queries) ListOrderHistoryByOrderID(ctx context.Context, orderID string) ([]OrderHistory, error) {
	rows, err := q.db.Query(ctx, listOrderHistoryByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderHistory
	for rows.Next() {
		var i OrderHistory
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.FromStatus,
			&i.ToStatus,
			&i.ChangedBy,
			&i.ActorType,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
