// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order_items.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrderItemsBatch = `-- name: CreateOrderItemsBatch :exec
INSERT INTO order_items (
    id,
    order_id,
    inventory_id,
    sku_id,
    sku_code,
    product_id,
    product_name,
    image_url,
    quantity,
    base_price,
    item_subtotal,
    currency,
    created_at
)
SELECT
    unnest($1::uuid[]),
    $2::text,
    unnest($3::uuid[]),
    unnest($4::uuid[]),
    unnest($5::text[]),
    unnest($6::uuid[]),
    unnest($7::text[]),
    unnest($8::text[]),
    unnest($9::bigint[]),
    unnest($10::bigint[]),
    unnest($11::bigint[]),
    $12::text,
    $13::timestamptz
`

type CreateOrderItemsBatchParams struct {
	Ids           []pgtype.UUID
	OrderID       string
	InventoryIds  []pgtype.UUID
	SkuIds        []pgtype.UUID
	SkuCodes      []string
	ProductIds    []pgtype.UUID
	ProductNames  []string
	ImageUrls     []string
	Quantities    []int64
	BasePrices    []int64
	ItemSubtotals []int64
	Currency      string
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) CreateOrderItemsBatch(ctx context.Context, arg CreateOrderItemsBatchParams) error {
	_, err := q.db.Exec(ctx, createOrderItemsBatch,
		arg.Ids,
		arg.OrderID,
		arg.InventoryIds,
		arg.SkuIds,
		arg.SkuCodes,
		arg.ProductIds,
		arg.ProductNames,
		arg.ImageUrls,
		arg.Quantities,
		arg.BasePrices,
		arg.ItemSubtotals,
		arg.Currency,
		arg.CreatedAt,
	)
	return err
}

const listOrderItemsByOrderID = `-- name: ListOrderItemsByOrderID :many
SELECT id, order_id, inventory_id, sku_id, sku_code, product_id, product_name, image_url, quantity, base_price, item_subtotal, currency, created_at
FROM order_items
WHERE order_id = $1::text
ORDER BY created_at ASC
`

func (q *Queries) ListOrderItemsByOrderID(ctx context.Context, orderID string) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, listOrderItemsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.InventoryID,
			&i.SkuID,
			&i.SkuCode,
			&i.ProductID,
			&i.ProductName,
			&i.ImageUrl,
			&i.Quantity,
			&i.BasePrice,
			&i.ItemSubtotal,
			&i.Currency,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
